In [1]:
# reprendre nettoyage

import sys
sys.path.append('..')

from utils.fonctions import load_parquet_data, normalize_colnames_list
from src.artifacts.data_processing import Nettoyage

TARGET_COL = 'consommation_annuelle_moyenne_par_logement_de_l_adresse_kwh_enedis_with_ban'

In [13]:
# custom functions
get_conso_colnames = lambda data: list(filter(lambda c: 'conso' in c, data.columns))
get_deperdition_colnames = lambda data: list(filter(lambda c: 'deperdition' in c, data.columns))
get_dpe_colnames = lambda data: list(filter(lambda c: 'dpe' in c, data.columns))



def numerize(data, encoding_pipeline, downcast_num_cols=True):

    def downcast_numeric_cols():
        # int32 range = 2**32/2 à gauche et à droite de 0
        for c in data.columns:
            if data[c].dtype == 'int64':
                data[c] = data[c].astype('int32')
            elif data[c].dtype == 'float64':
                data[c] = data[c].astype('float32')
        return data
    
    encoding_pipeline.set_output(transform='pandas')
    data = encoding_pipeline.fit_transform(data)

    if downcast_num_cols:
        return downcast_numeric_cols()
    return data

In [3]:
df = load_parquet_data('../ressources/data/2_intermediary/enedis_ban_ademe_extract_PARIS_2022.parquet')

pipeline = Nettoyage(df)

pipeline.run(use_entropy_selection = True)
df_clean_v1 = pipeline.df

del df

Loading parquet data from : ../ressources/data/2_intermediary/enedis_ban_ademe_extract_PARIS_2022.parquet..
-> Delete cols mano..
-> Delete NaN cols..
Le dataframe contient initialement 250 colonnes et 464576 lignes.
Start processing : columns identification..
Il y a 76 colonnes vides à au moins, 90.0%, 55 colonnes avec une entropie de 0 ou 1 et 13 colonnes inutiles
Start processing : columns deleting ...
Il reste 146 colonnes et 375231 lignes.
-> Start object columns auto casting..
End casting
-> Fill pd.NA for float dtypes..
Done fillnan !
Les colonnes suivantes ont une corrélation supérieure à 0.9 : ['emission_ges_chauffage_energie_ndeg1_ademe', 'conso_chauffage_installation_chauffage_ndeg1_ademe', 'emission_ges_5_usages_energie_ndeg1_ademe', 'conso_ecs_e_primaire_ademe', 'emission_ges_eclairage_ademe', 'conso_e_finale_depensier_generateur_ecs_ndeg1_ademe', 'cout_chauffage_energie_ndeg1_ademe', 'conso_chauffage_generateur_ndeg1_installation_ndeg1_ademe', 'emission_ges_ecs_ademe', 'emission_ges_ecs_depensier_ademe', 'emission_ges_5_usages_ademe', 'apports_internes_saison_chauffe_ademe', 'conso_e_finale_generateur_ecs_ndeg1_ademe', 'conso_refroidissement_depensier_e_primaire_ademe', 'deperditions_enveloppe_ademe', 'surface_habitable_desservie_par_installation_ecs_ademe', 'emission_ges_auxiliaires_ademe', 'conso_ecs_depensier_e_finale_ademe', 'cout_chauffage_depensier_ademe', 'conso_refroidissement_e_primaire_ademe', 'conso_ecs_e_finale_ademe', 'cout_total_5_usages_energie_ndeg2_ademe', 'cout_total_5_usages_ademe', 'cout_eclairage_ademe', 'cout_ecs_energie_ndeg1_ademe', 'conso_5_usages_e_finale_energie_ndeg1_ademe', 'conso_chauffage_e_finale_energie_ndeg1_ademe', 'deperditions_murs_ademe', 'surface_chauffee_installation_chauffage_ndeg1_ademe', 'cout_ecs_ademe', 'conso_eclairage_e_primaire_ademe', 'conso_chauffage_e_finale_ademe', 'deperditions_ponts_thermiques_ademe', 'conso_chauffage_depensier_e_finale_ademe', 'conso_eclairage_e_finale_ademe', 'conso_ecs_e_finale_energie_ndeg1_ademe', 'conso_chauffage_depensier_generateur_ndeg1_installation_ndeg1_ademe', 'cout_ecs_energie_ndeg2_ademe', 'cout_chauffage_ademe', 'conso_chauffage_e_primaire_ademe', 'deperditions_renouvellement_air_ademe', 'emission_ges_chauffage_depensier_ademe', 'conso_refroidissement_depensier_e_finale_ademe', 'conso_5_usages_e_finale_ademe', 'conso_e_finale_installation_ecs_ademe', 'conso_5_usages_e_primaire_ademe', 'conso_auxiliaires_e_finale_ademe', 'conso_chauffage_e_finale_energie_ndeg2_ademe', 'emission_ges_chauffage_ademe', 'emission_ges_ecs_energie_ndeg1_ademe', 'cout_ecs_depensier_ademe', 'cout_total_5_usages_energie_ndeg1_ademe', 'besoin_ecs_ademe']
Les colonnes suivantes ont été supprimées : ['emission_ges_chauffage_energie_ndeg1_ademe', 'conso_chauffage_installation_chauffage_ndeg1_ademe', 'emission_ges_5_usages_energie_ndeg1_ademe', 'conso_ecs_e_primaire_ademe', 'emission_ges_eclairage_ademe', 'conso_e_finale_depensier_generateur_ecs_ndeg1_ademe', 'cout_chauffage_energie_ndeg1_ademe', 'conso_chauffage_generateur_ndeg1_installation_ndeg1_ademe', 'emission_ges_ecs_ademe', 'emission_ges_ecs_depensier_ademe', 'emission_ges_5_usages_ademe', 'apports_internes_saison_chauffe_ademe', 'conso_e_finale_generateur_ecs_ndeg1_ademe', 'conso_refroidissement_depensier_e_primaire_ademe', 'deperditions_enveloppe_ademe', 'surface_habitable_desservie_par_installation_ecs_ademe', 'emission_ges_auxiliaires_ademe', 'conso_ecs_depensier_e_finale_ademe', 'cout_chauffage_depensier_ademe', 'conso_refroidissement_e_primaire_ademe', 'conso_ecs_e_finale_ademe', 'cout_total_5_usages_energie_ndeg2_ademe', 'cout_total_5_usages_ademe', 'cout_eclairage_ademe', 'cout_ecs_energie_ndeg1_ademe', 'conso_5_usages_e_finale_energie_ndeg1_ademe', 'conso_chauffage_e_finale_energie_ndeg1_ademe', 'deperditions_murs_ademe', 'surface_chauffee_installation_chauffage_ndeg1_ademe', 'cout_ecs_ademe', 'conso_eclairage_e_primaire_ademe', 'conso_chauffage_e_finale_ademe', 'deperditions_ponts_thermiques_ademe', 'conso_chauffage_depensier_e_finale_ademe', 'conso_eclairage_e_finale_ademe', 'conso_ecs_e_finale_energie_ndeg1_ademe', 'conso_chauffage_depensier_generateur_ndeg1_installation_ndeg1_ademe', 'cout_ecs_energie_ndeg2_ademe', 'cout_chauffage_ademe', 'conso_chauffage_e_primaire_ademe', 'deperditions_renouvellement_air_ademe', 'emission_ges_chauffage_depensier_ademe', 'conso_refroidissement_depensier_e_finale_ademe', 'conso_5_usages_e_finale_ademe', 'conso_e_finale_installation_ecs_ademe', 'conso_5_usages_e_primaire_ademe', 'conso_auxiliaires_e_finale_ademe', 'conso_chauffage_e_finale_energie_ndeg2_ademe', 'emission_ges_chauffage_ademe', 'emission_ges_ecs_energie_ndeg1_ademe', 'cout_ecs_depensier_ademe', 'cout_total_5_usages_energie_ndeg1_ademe', 'besoin_ecs_ademe']
Il reste 93 colonnes
Il y a 4 colonnes de dates à supprimer..
Le nettoyage a duré : 0:03:02.071900
====================================================================================================

In [6]:
df_clean_v1.dtypes.value_counts()

float32           50
string[python]    39
Name: count, dtype: int64

In [17]:
df = load_parquet_data('../ressources/data/2_intermediary/enedis_ban_ademe_extract_PARIS_2022.parquet')

pipeline = Nettoyage(df)

pipeline.run(use_target_correlation_selection=True)
df_clean_v2 = pipeline.df

del df

Loading parquet data from : ../ressources/data/2_intermediary/enedis_ban_ademe_extract_PARIS_2022.parquet..

-> Delete cols mano..
-> Delete NaN cols..
Le dataframe contient initialement 250 colonnes et 464576 lignes.
Start processing : columns identification..
Il y a 76 colonnes vides à au moins, 90.0%, 55 colonnes avec une entropie de 0 ou 1 et 13 colonnes inutiles
Start processing : columns deleting ...
Il reste 146 colonnes et 375231 lignes.
-> Start object columns auto casting..
End casting
-> Fill pd.NA for float dtypes..
Done fillnan !
Les colonnes suivantes ont une corrélation supérieure à 0.9 : ['emission_ges_chauffage_energie_ndeg1_ademe', 'conso_chauffage_depensier_installation_chauffage_ndeg1_ademe', 'conso_chauffage_installation_chauffage_ndeg1_ademe', 'emission_ges_5_usages_energie_ndeg1_ademe', 'cout_refroidissement_depensier_ademe', 'emission_ges_eclairage_ademe', 'conso_e_finale_depensier_generateur_ecs_ndeg1_ademe', 'cout_chauffage_energie_ndeg1_ademe', 'conso_chauffage_generateur_ndeg1_installation_ndeg1_ademe', 'emission_ges_ecs_ademe', 'emission_ges_ecs_depensier_ademe', 'emission_ges_5_usages_ademe', 'apports_internes_saison_chauffe_ademe', 'conso_e_finale_generateur_ecs_ndeg1_ademe', 'deperditions_enveloppe_ademe', 'conso_refroidissement_e_finale_ademe', 'surface_habitable_desservie_par_installation_ecs_ademe', 'emission_ges_auxiliaires_ademe', 'conso_ecs_depensier_e_finale_ademe', 'cout_chauffage_depensier_ademe', 'conso_chauffage_depensier_e_primaire_ademe', 'conso_refroidissement_e_primaire_ademe', 'conso_ecs_e_finale_ademe', 'cout_total_5_usages_energie_ndeg2_ademe', 'conso_e_finale_depensier_installation_ecs_ademe', 'cout_total_5_usages_ademe', 'cout_eclairage_ademe', 'emission_ges_chauffage_energie_ndeg2_ademe', 'conso_chauffage_e_finale_energie_ndeg1_ademe', 'conso_5_usages_e_finale_energie_ndeg1_ademe', 'cout_refroidissement_ademe', 'deperditions_murs_ademe', 'surface_chauffee_installation_chauffage_ndeg1_ademe', 'cout_ecs_ademe', 'conso_eclairage_e_primaire_ademe', 'conso_chauffage_e_finale_ademe', 'conso_chauffage_depensier_e_finale_ademe', 'conso_eclairage_e_finale_ademe', 'conso_ecs_e_finale_energie_ndeg1_ademe', 'conso_chauffage_depensier_generateur_ndeg1_installation_ndeg1_ademe', 'besoin_chauffage_ademe', 'conso_ecs_e_finale_energie_ndeg2_ademe', 'cout_chauffage_ademe', 'conso_chauffage_e_primaire_ademe', 'deperditions_renouvellement_air_ademe', 'emission_ges_chauffage_depensier_ademe', 'conso_5_usages_e_finale_ademe', 'conso_ecs_depensier_e_primaire_ademe', 'conso_5_usages_e_primaire_ademe', 'conso_auxiliaires_e_finale_ademe', 'emission_ges_chauffage_ademe', 'emission_ges_ecs_energie_ndeg1_ademe', 'cout_ecs_depensier_ademe']
Les colonnes suivantes ont été supprimées : ['emission_ges_chauffage_energie_ndeg1_ademe', 'conso_chauffage_depensier_installation_chauffage_ndeg1_ademe', 'conso_chauffage_installation_chauffage_ndeg1_ademe', 'emission_ges_5_usages_energie_ndeg1_ademe', 'cout_refroidissement_depensier_ademe', 'emission_ges_eclairage_ademe', 'conso_e_finale_depensier_generateur_ecs_ndeg1_ademe', 'cout_chauffage_energie_ndeg1_ademe', 'conso_chauffage_generateur_ndeg1_installation_ndeg1_ademe', 'emission_ges_ecs_ademe', 'emission_ges_ecs_depensier_ademe', 'emission_ges_5_usages_ademe', 'apports_internes_saison_chauffe_ademe', 'conso_e_finale_generateur_ecs_ndeg1_ademe', 'deperditions_enveloppe_ademe', 'conso_refroidissement_e_finale_ademe', 'surface_habitable_desservie_par_installation_ecs_ademe', 'emission_ges_auxiliaires_ademe', 'conso_ecs_depensier_e_finale_ademe', 'cout_chauffage_depensier_ademe', 'conso_chauffage_depensier_e_primaire_ademe', 'conso_refroidissement_e_primaire_ademe', 'conso_ecs_e_finale_ademe', 'cout_total_5_usages_energie_ndeg2_ademe', 'conso_e_finale_depensier_installation_ecs_ademe', 'cout_total_5_usages_ademe', 'cout_eclairage_ademe', 'emission_ges_chauffage_energie_ndeg2_ademe', 'conso_chauffage_e_finale_energie_ndeg1_ademe', 'conso_5_usages_e_finale_energie_ndeg1_ademe', 'cout_refroidissement_ademe', 'deperditions_murs_ademe', 'surface_chauffee_installation_chauffage_ndeg1_ademe', 'cout_ecs_ademe', 'conso_eclairage_e_primaire_ademe', 'conso_chauffage_e_finale_ademe', 'conso_chauffage_depensier_e_finale_ademe', 'conso_eclairage_e_finale_ademe', 'conso_ecs_e_finale_energie_ndeg1_ademe', 'conso_chauffage_depensier_generateur_ndeg1_installation_ndeg1_ademe', 'besoin_chauffage_ademe', 'conso_ecs_e_finale_energie_ndeg2_ademe', 'cout_chauffage_ademe', 'conso_chauffage_e_primaire_ademe', 'deperditions_renouvellement_air_ademe', 'emission_ges_chauffage_depensier_ademe', 'conso_5_usages_e_finale_ademe', 'conso_ecs_depensier_e_primaire_ademe', 'conso_5_usages_e_primaire_ademe', 'conso_auxiliaires_e_finale_ademe', 'emission_ges_chauffage_ademe', 'emission_ges_ecs_energie_ndeg1_ademe', 'cout_ecs_depensier_ademe']
Il reste 93 colonnes
Il y a 4 colonnes de dates à supprimer..
Le nettoyage a duré : 0:01:17.959548
====================================================================================================

In [18]:
df_clean_v2.dtypes.value_counts()

float32           50
string[python]    39
Name: count, dtype: int64

In [8]:
import category_encoders as ce
from sklearn.compose import ColumnTransformer

### Encodage dataframe v1 (use entropy selection)

*A ce niveau la partie nettoyage de data est finie (version mvp) est ok. On va faire un pieplien d'encoding ici.*

In [5]:
df_clean_v1[df_clean_v1.isna().sum().loc[df_clean_v1.isna().sum().values > 0].index].dtypes

# les na dans les col de type non numeric (exple string)
# et garder les dates ?

configuration_installation_chauffage_ndeg1_ademe          string[python]
configuration_installation_ecs_ademe                      string[python]
type_installation_chauffage_ndeg1_ademe                   string[python]
type_installation_ecs_general_ademe                       string[python]
usage_generateur_ecs_ndeg1_ademe                          string[python]
type_energie_generateur_ecs_ndeg1_ademe                   string[python]
type_generateur_ecs_ndeg1_ademe                           string[python]
logement_traversant_0_1_ademe                             string[python]
qualite_isolation_murs_ademe                              string[python]
type_emetteur_installation_chauffage_ndeg1_ademe          string[python]
classe_inertie_batiment_ademe                             string[python]
indicateur_confort_ete_ademe                              string[python]
type_energie_ndeg2_ademe                                  string[python]
type_installation_ecs_ademe                               string[python]
presence_brasseur_air_0_1_ademe                           string[python]
qualite_isolation_plancher_haut_comble_perdu_ademe        string[python]
protection_solaire_exterieure_0_1_ademe                   string[python]
usage_generateur_ndeg1_installation_ndeg1_ademe           string[python]
type_energie_generateur_ndeg1_installation_ndeg1_ademe    string[python]
type_installation_chauffage_ademe                         string[python]
type_energie_principale_chauffage_ademe                   string[python]
inertie_lourde_0_1_ademe                                  string[python]
isolation_toiture_0_1_ademe                               string[python]
type_generateur_ndeg1_installation_ndeg1_ademe            string[python]
qualite_isolation_plancher_bas_ademe                      string[python]
type_energie_principale_ecs_ademe                         string[python]
qualite_isolation_plancher_haut_toit_terrase_ademe        string[python]
categorie_enr_ademe                                       string[python]
appartement_non_visite_0_1_ademe                          string[python]
dtype: object

In [6]:
# type string
df_clean_v1.select_dtypes(include='string').head()

,configuration_installation_chauffage_ndeg1_ademe,configuration_installation_ecs_ademe,type_installation_chauffage_ndeg1_ademe,type_installation_ecs_general_ademe,usage_generateur_ecs_ndeg1_ademe,type_energie_generateur_ecs_ndeg1_ademe,type_generateur_ecs_ndeg1_ademe,logement_traversant_0_1_ademe,qualite_isolation_menuiseries_ademe,qualite_isolation_murs_ademe,...,etiquette_ges_ademe,etiquette_dpe_ademe,type_generateur_ndeg1_installation_ndeg1_ademe,qualite_isolation_plancher_bas_ademe,type_energie_principale_ecs_ademe,qualite_isolation_plancher_haut_toit_terrase_ademe,categorie_enr_ademe,appartement_non_visite_0_1_ademe,type_enedis_with_ban,arrondissement
0,Installation de chauffage simple,Un seul système d'ECS sans solaire,installation individuelle,individuel,chauffage + ecs,Gaz naturel,Chaudière gaz à condensation après 2015,True,très bonne,insuffisante,...,C,C,Chaudière gaz à condensation après 2015,très bonne,Gaz naturel,<NA>,<NA>,<NA>,housenumber,6
1,Installation de chauffage simple,Un seul système d'ECS sans solaire,installation individuelle,individuel,ecs,Électricité,Ballon électrique à accumulation vertical Caté...,False,insuffisante,insuffisante,...,B,D,Radiateur électrique à accumulation,très bonne,Électricité,<NA>,<NA>,<NA>,housenumber,6
2,Installation de chauffage simple,Un seul système d'ECS sans solaire,installation individuelle,individuel,ecs,Électricité,Ballon électrique à accumulation horizontal,True,insuffisante,insuffisante,...,D,E,Chaudière gaz basse température 2001-2015,très bonne,Électricité,<NA>,<NA>,<NA>,housenumber,6
3,Installation de chauffage simple,Un seul système d'ECS sans solaire,installation individuelle,individuel,ecs,Électricité,Ballon électrique à accumulation vertical Caté...,False,moyenne,insuffisante,...,C,F,Radiateur électrique à accumulation,très bonne,Électricité,<NA>,<NA>,<NA>,housenumber,6
4,Installation de chauffage simple,Un seul système d'ECS sans solaire,installation individuelle,individuel,ecs,Électricité,Ballon électrique à accumulation vertical Caté...,True,bonne,insuffisante,...,C,F,Radiateur électrique à accumulation,très bonne,Électricité,<NA>,<NA>,<NA>,housenumber,6

In [7]:
categ_cols_init = set(df_clean_v1.select_dtypes(include='string').columns)
categ_cols = categ_cols_init.copy()

# decomposer les colonnes par groupes pour appliquer encodage
# on traite au cas par cas pour identifier les cols à ordinal_encoder et on labelisera tout le reste
# observer la data

In [ ]:
# qualite cols ademe
get_qualite_col_ademe = lambda data: list(filter(lambda c: ('qualite' in c) and ('ademe' in c), data))

for _ in df_clean_v1[get_qualite_col_ademe(df_clean_v1)]:
    print(df_clean_v1[_].value_counts(dropna=False))

print(df_clean_v1['indicateur_confort_ete_ademe'].value_counts())

# mapping ordinal encoder for quality cols
mapping_oe_qualite_col_ademe = {'insuffisante': 1, 'moyenne': 2, 'bonne': 3, 'très bonne': 4, '<NA>': -1}
to_oe_qualite_col_ademe = [
        'qualite_isolation_menuiseries_ademe',
        'qualite_isolation_murs_ademe',
        'qualite_isolation_plancher_haut_comble_perdu_ademe',
        'qualite_isolation_enveloppe_ademe',
        'qualite_isolation_plancher_bas_ademe',
        'qualite_isolation_plancher_haut_toit_terrase_ademe',
        'indicateur_confort_ete_ademe'
    ]

In [9]:
categ_cols -= set(to_oe_qualite_col_ademe)

In [10]:
df_clean_v1.select_dtypes(include='string')[list(categ_cols)].head()

,type_energie_principale_chauffage_ademe,etiquette_dpe_ademe,type_energie_ndeg2_ademe,classe_inertie_batiment_ademe,etiquette_ges_ademe,usage_generateur_ecs_ndeg1_ademe,categorie_enr_ademe,logement_traversant_0_1_ademe,inertie_lourde_0_1_ademe,type_energie_principale_ecs_ademe,...,configuration_installation_chauffage_ndeg1_ademe,protection_solaire_exterieure_0_1_ademe,usage_generateur_ndeg1_installation_ndeg1_ademe,isolation_toiture_0_1_ademe,configuration_installation_ecs_ademe,methode_application_dpe_ademe,type_installation_ecs_general_ademe,type_energie_generateur_ndeg1_installation_ndeg1_ademe,type_generateur_ecs_ndeg1_ademe,type_generateur_ndeg1_installation_ndeg1_ademe
0,Gaz naturel,C,Électricité,Moyenne,C,chauffage + ecs,<NA>,True,False,Gaz naturel,...,Installation de chauffage simple,True,chauffage + ecs,False,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Gaz naturel,Chaudière gaz à condensation après 2015,Chaudière gaz à condensation après 2015
1,Électricité,D,<NA>,Moyenne,B,ecs,<NA>,False,False,Électricité,...,Installation de chauffage simple,False,chauffage,True,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Électricité,Ballon électrique à accumulation vertical Caté...,Radiateur électrique à accumulation
2,Gaz naturel,E,Électricité,Moyenne,D,ecs,<NA>,True,False,Électricité,...,Installation de chauffage simple,False,chauffage,False,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Gaz naturel,Ballon électrique à accumulation horizontal,Chaudière gaz basse température 2001-2015
3,Électricité,F,<NA>,Moyenne,C,ecs,<NA>,False,False,Électricité,...,Installation de chauffage simple,False,chauffage,True,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Électricité,Ballon électrique à accumulation vertical Caté...,Radiateur électrique à accumulation
4,Électricité,F,<NA>,Moyenne,C,ecs,<NA>,True,False,Électricité,...,Installation de chauffage simple,False,chauffage,True,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Électricité,Ballon électrique à accumulation vertical Caté...,Radiateur électrique à accumulation

In [ ]:
# traiter les colonnes True/False

get_binary_cols_ademe = lambda data: list(filter(lambda c: ('0_1' in c) and ('ademe' in c), data))

for _ in df_clean_v1[get_binary_cols_ademe(df_clean_v1)]:
    print(df_clean_v1[_].value_counts(dropna=False))

# mapping binary cols ademe
mapping_binary_col_ademe = {'True': 1, 'False': 0, '<NA>': -1} # pertinent car on n'a pas le type bool donc si on labelisait, l'encoder pourrait inverser 0 et 1 selon la colonne 
                                                               # on peut forcer le mapping surout à cause des NA
to_binary_col_ademe = [
        'logement_traversant_0_1_ademe',
        'presence_brasseur_air_0_1_ademe',
        'protection_solaire_exterieure_0_1_ademe',
        'inertie_lourde_0_1_ademe',
        'isolation_toiture_0_1_ademe',
        'appartement_non_visite_0_1_ademe'
    ]

In [12]:
categ_cols -= set(to_binary_col_ademe)

In [14]:
df_clean_v1.select_dtypes(include='string')[list(categ_cols)].head()

,type_energie_principale_chauffage_ademe,etiquette_dpe_ademe,type_energie_ndeg2_ademe,classe_inertie_batiment_ademe,etiquette_ges_ademe,usage_generateur_ecs_ndeg1_ademe,categorie_enr_ademe,type_energie_principale_ecs_ademe,type_energie_ndeg1_ademe,type_energie_generateur_ecs_ndeg1_ademe,...,type_batiment_ademe,type_installation_chauffage_ademe,configuration_installation_chauffage_ndeg1_ademe,usage_generateur_ndeg1_installation_ndeg1_ademe,configuration_installation_ecs_ademe,methode_application_dpe_ademe,type_installation_ecs_general_ademe,type_energie_generateur_ndeg1_installation_ndeg1_ademe,type_generateur_ecs_ndeg1_ademe,type_generateur_ndeg1_installation_ndeg1_ademe
0,Gaz naturel,C,Électricité,Moyenne,C,chauffage + ecs,<NA>,Gaz naturel,Gaz naturel,Gaz naturel,...,appartement,individuel,Installation de chauffage simple,chauffage + ecs,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Gaz naturel,Chaudière gaz à condensation après 2015,Chaudière gaz à condensation après 2015
1,Électricité,D,<NA>,Moyenne,B,ecs,<NA>,Électricité,Électricité,Électricité,...,appartement,individuel,Installation de chauffage simple,chauffage,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Électricité,Ballon électrique à accumulation vertical Caté...,Radiateur électrique à accumulation
2,Gaz naturel,E,Électricité,Moyenne,D,ecs,<NA>,Électricité,Gaz naturel,Électricité,...,appartement,individuel,Installation de chauffage simple,chauffage,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Gaz naturel,Ballon électrique à accumulation horizontal,Chaudière gaz basse température 2001-2015
3,Électricité,F,<NA>,Moyenne,C,ecs,<NA>,Électricité,Électricité,Électricité,...,appartement,individuel,Installation de chauffage simple,chauffage,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Électricité,Ballon électrique à accumulation vertical Caté...,Radiateur électrique à accumulation
4,Électricité,F,<NA>,Moyenne,C,ecs,<NA>,Électricité,Électricité,Électricité,...,appartement,individuel,Installation de chauffage simple,chauffage,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Électricité,Ballon électrique à accumulation vertical Caté...,Radiateur électrique à accumulation

In [ ]:
# etiquettes ademe # dont DPE  # CLASSES A - G
get_etiquette_ademe_cols_ordinal = lambda data: list(filter(lambda c: ('etiquette' in c) and ('ademe' in c), data))

to_oe_etiquettes_ademe = ['etiquette_ges_ademe', 'etiquette_dpe_ademe']

for _ in to_oe_etiquettes_ademe:
    print(df_clean_v1[_].value_counts(dropna=False))

mapping_to_oe_etiquette_ademe = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, '<NA>': -1}

In [16]:
categ_cols -= set(to_oe_etiquettes_ademe)

In [17]:
df_clean_v1.select_dtypes(include='string')[list(categ_cols)].head()

,type_energie_principale_chauffage_ademe,type_energie_ndeg2_ademe,classe_inertie_batiment_ademe,usage_generateur_ecs_ndeg1_ademe,categorie_enr_ademe,type_energie_principale_ecs_ademe,type_energie_ndeg1_ademe,type_energie_generateur_ecs_ndeg1_ademe,type_enedis_with_ban,type_emetteur_installation_chauffage_ndeg1_ademe,...,type_batiment_ademe,type_installation_chauffage_ademe,configuration_installation_chauffage_ndeg1_ademe,usage_generateur_ndeg1_installation_ndeg1_ademe,configuration_installation_ecs_ademe,methode_application_dpe_ademe,type_installation_ecs_general_ademe,type_energie_generateur_ndeg1_installation_ndeg1_ademe,type_generateur_ecs_ndeg1_ademe,type_generateur_ndeg1_installation_ndeg1_ademe
0,Gaz naturel,Électricité,Moyenne,chauffage + ecs,<NA>,Gaz naturel,Gaz naturel,Gaz naturel,housenumber,Radiateur bitube sans robinet thermostatique s...,...,appartement,individuel,Installation de chauffage simple,chauffage + ecs,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Gaz naturel,Chaudière gaz à condensation après 2015,Chaudière gaz à condensation après 2015
1,Électricité,<NA>,Moyenne,ecs,<NA>,Électricité,Électricité,Électricité,housenumber,Radiateur électrique à accumulation,...,appartement,individuel,Installation de chauffage simple,chauffage,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Électricité,Ballon électrique à accumulation vertical Caté...,Radiateur électrique à accumulation
2,Gaz naturel,Électricité,Moyenne,ecs,<NA>,Électricité,Gaz naturel,Électricité,housenumber,Radiateur monotube sans robinet thermostatique...,...,appartement,individuel,Installation de chauffage simple,chauffage,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Gaz naturel,Ballon électrique à accumulation horizontal,Chaudière gaz basse température 2001-2015
3,Électricité,<NA>,Moyenne,ecs,<NA>,Électricité,Électricité,Électricité,housenumber,Radiateur électrique à accumulation,...,appartement,individuel,Installation de chauffage simple,chauffage,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Électricité,Ballon électrique à accumulation vertical Caté...,Radiateur électrique à accumulation
4,Électricité,<NA>,Moyenne,ecs,<NA>,Électricité,Électricité,Électricité,housenumber,Radiateur électrique à accumulation,...,appartement,individuel,Installation de chauffage simple,chauffage,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Électricité,Ballon électrique à accumulation vertical Caté...,Radiateur électrique à accumulation

In [18]:
# 
to_oe_classe_inertie_bat_ademe = ['classe_inertie_batiment_ademe']
mapping_oe_classe_inertie_bat_ademe = {'Légère': 1, 'Moyenne': 2, 'Lourde': 3, 'Très lourde': 4, '<NA>': -1}

df_clean_v1['classe_inertie_batiment_ademe'].value_counts(dropna=False)

classe_inertie_batiment_ademe
Légère         127686
Moyenne        116712
Lourde          85261
Très lourde     36407
<NA>             3015
Name: count, dtype: Int64

In [19]:
categ_cols -= set(to_oe_classe_inertie_bat_ademe)

In [20]:
df_clean_v1.select_dtypes(include='string')[list(categ_cols)].head()

,type_energie_principale_chauffage_ademe,type_energie_ndeg2_ademe,usage_generateur_ecs_ndeg1_ademe,categorie_enr_ademe,type_energie_principale_ecs_ademe,type_energie_ndeg1_ademe,type_energie_generateur_ecs_ndeg1_ademe,type_enedis_with_ban,type_emetteur_installation_chauffage_ndeg1_ademe,type_installation_chauffage_ndeg1_ademe,...,type_batiment_ademe,type_installation_chauffage_ademe,configuration_installation_chauffage_ndeg1_ademe,usage_generateur_ndeg1_installation_ndeg1_ademe,configuration_installation_ecs_ademe,methode_application_dpe_ademe,type_installation_ecs_general_ademe,type_energie_generateur_ndeg1_installation_ndeg1_ademe,type_generateur_ecs_ndeg1_ademe,type_generateur_ndeg1_installation_ndeg1_ademe
0,Gaz naturel,Électricité,chauffage + ecs,<NA>,Gaz naturel,Gaz naturel,Gaz naturel,housenumber,Radiateur bitube sans robinet thermostatique s...,installation individuelle,...,appartement,individuel,Installation de chauffage simple,chauffage + ecs,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Gaz naturel,Chaudière gaz à condensation après 2015,Chaudière gaz à condensation après 2015
1,Électricité,<NA>,ecs,<NA>,Électricité,Électricité,Électricité,housenumber,Radiateur électrique à accumulation,installation individuelle,...,appartement,individuel,Installation de chauffage simple,chauffage,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Électricité,Ballon électrique à accumulation vertical Caté...,Radiateur électrique à accumulation
2,Gaz naturel,Électricité,ecs,<NA>,Électricité,Gaz naturel,Électricité,housenumber,Radiateur monotube sans robinet thermostatique...,installation individuelle,...,appartement,individuel,Installation de chauffage simple,chauffage,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Gaz naturel,Ballon électrique à accumulation horizontal,Chaudière gaz basse température 2001-2015
3,Électricité,<NA>,ecs,<NA>,Électricité,Électricité,Électricité,housenumber,Radiateur électrique à accumulation,installation individuelle,...,appartement,individuel,Installation de chauffage simple,chauffage,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Électricité,Ballon électrique à accumulation vertical Caté...,Radiateur électrique à accumulation
4,Électricité,<NA>,ecs,<NA>,Électricité,Électricité,Électricité,housenumber,Radiateur électrique à accumulation,installation individuelle,...,appartement,individuel,Installation de chauffage simple,chauffage,Un seul système d'ECS sans solaire,dpe appartement individuel,individuel,Électricité,Ballon électrique à accumulation vertical Caté...,Radiateur électrique à accumulation

In [21]:
to_oe_periode_construction = ['periode_construction_ademe']
mapping_periode_construction = {
    "avant 1948": 1,
    "1948-1974": 2,
    "1975-1977": 3,
    "1978-1982": 4,
    "1983-1988": 5,
    "1989-2000": 6,
    "2001-2005": 7,
    "2006-2012": 8,
    "2013-2021": 9,
    "après 2021": 10
    }

df_clean_v1['periode_construction_ademe'].value_counts(dropna=False).sort_index()
# il y a un ordre qui n'est pas respecté quand on sort l'index

periode_construction_ademe
1948-1974      67497
1975-1977       9457
1978-1982       8131
1983-1988       9412
1989-2000      20057
2001-2005       3479
2006-2012       2538
2013-2021       4452
après 2021       588
avant 1948    243470
Name: count, dtype: Int64

In [22]:
categ_cols -= set(to_oe_periode_construction)

In [24]:
ov = {}
for _ in df_clean_v1.select_dtypes(include='string')[list(categ_cols)]:
    ov.update({_ : df_clean_v1[_].value_counts(dropna=False).to_dict()})

ov

{'type_energie_principale_chauffage_ademe': {'Électricité': 165167,
  'Gaz naturel': 137375,
  'Réseau de Chauffage urbain': 50706,
  <NA>: 10189,
  'Fioul domestique': 5058,
  'GPL': 455,
  'Bois – Bûches': 83,
  'Bois – Granulés (pellets) ou briquettes': 26,
  'Propane': 8,
  'Charbon': 5,
  'Bois – Plaquettes forestières': 4,
  'Butane': 4,
  'Réseau de Froid Urbain': 1},
 'type_energie_ndeg2_ademe': {'Électricité': 194409,
  <NA>: 164769,
  'Gaz naturel': 7874,
  'Réseau de Chauffage urbain': 1449,
  'Fioul domestique': 299,
  'Bois – Bûches': 213,
  'GPL': 32,
  'Bois – Granulés (pellets) ou briquettes': 21,
  "Électricité d'origine renouvelable utilisée dans le bâtiment": 7,
  'Bois – Plaquettes forestières': 4,
  'Bois – Plaquettes d’industrie': 3,
  'Réseau de Froid Urbain': 1},
 'usage_generateur_ecs_ndeg1_ademe': {'ecs': 198685,
  'chauffage + ecs': 151860,
  <NA>: 12337,
  'chauffage': 6199},
 'categorie_enr_ademe': {<NA>: 323553,
  'réseau de chaleur ou de froid vertueux': 37699,
  'pompe à chaleur': 3746,
  'Il existe plusieurs descriptifs ENR': 1363,
  'panneaux solaires thermiques': 913,
  'chauffe-eau thermodynamique': 906,
  'géothermie': 388,
  'chauffage au bois': 279,
  'cogénération': 124,
  'panneaux solaires photovoltaïques': 110},
 'type_energie_principale_ecs_ademe': {'Électricité': 191327,
  'Gaz naturel': 118358,
  'Réseau de Chauffage urbain': 43610,
  <NA>: 12337,
  'Fioul domestique': 3151,
  'GPL': 265,
  'Bois – Granulés (pellets) ou briquettes': 21,
  'Propane': 5,
  'Butane': 4,
  'Bois – Bûches': 3},
 'type_energie_ndeg1_ademe': {'Électricité': 173874,
  'Gaz naturel': 138509,
  'Réseau de Chauffage urbain': 50905,
  'Fioul domestique': 5175,
  'GPL': 499,
  'Bois – Bûches': 76,
  'Bois – Granulés (pellets) ou briquettes': 26,
  'Propane': 7,
  'Charbon': 5,
  'Butane': 4,
  'Réseau de Froid Urbain': 1},
 'type_energie_generateur_ecs_ndeg1_ademe': {'Électricité': 191375,
  'Gaz naturel': 118310,
  'Réseau de Chauffage urbain': 43612,
  <NA>: 12337,
  'Fioul domestique': 3151,
  'GPL': 263,
  'Bois – Granulés (pellets) ou briquettes': 21,
  'Propane': 5,
  'Butane': 4,
  'Bois – Bûches': 3},
 'type_enedis_with_ban': {'housenumber': 365937, 'street': 3144},
 'type_emetteur_installation_chauffage_ndeg1_ademe': {'radiateur électrique NFC, NF** et NF***': 52962,
  'Convecteur électrique NFC, NF** et NF***': 48870,
  'Radiateur bitube sans robinet thermostatique sur réseau collectif eau chaude haute température(sup ou egal 65°C)': 43666,
  'Panneau rayonnant NFC, NF** et NF***': 34072,
  'Radiateur bitube sans robinet thermostatique sur réseau collectif eau chaude basse ou moyenne température(inf 65°C)': 23483,
  'Radiateur électrique à accumulation': 17919,
  'Radiateur bitube avec robinet thermostatique sur réseau collectif eau chaude haute température(sup ou egal 65°C)': 16359,
  'Radiateur bitube sans robinet thermostatique sur réseau individuel eau chaude haute température(sup ou egal 65°C)': 16003,
  'Radiateur monotube sans robinet thermostatique sur réseau collectif eau chaude haute température(sup ou egal 65°C)': 15087,
  'Radiateur bitube sans robinet thermostatique sur réseau individuel eau chaude basse ou moyenne température(inf 65°C)': 13205,
  <NA>: 10418,
  'Plancher chauffant sur réseau collectif eau chaude haute température(sup ou egal 65°C)': 10414,
  'Radiateur bitube avec robinet thermostatique sur réseau collectif eau chaude basse ou moyenne température(inf 65°C)': 10193,
  'Radiateur monotube sans robinet thermostatique sur réseau individuel eau chaude haute température(sup ou egal 65°C)': 7413,
  'Radiateur bitube avec robinet thermostatique sur réseau individuel eau chaude basse ou moyenne température(inf 65°C)': 7016,
  'Radiateur bitube avec robinet thermostatique sur réseau individuel eau chaude haute température(sup ou egal 65°C)': 6417,
  'Autres émetteurs à effet joule': 5685,
  'Radiateur monotube avec robinet thermostatique sur réseau collectif eau chaude haute température(sup ou egal 65°C)': 5408,
  'Plancher chauffant sur réseau collectif eau chaude basse ou moyenne température(inf 65°C)': 3428,
  'Plancher chauffant sur réseau individuel eau chaude haute température(sup ou egal 65°C)': 3426,
  'Radiateur monotube sans robinet thermostatique sur réseau collectif eau chaude basse ou moyenne température(inf 65°C)': 3407,
  'Radiateur monotube avec robinet thermostatique sur réseau individuel eau chaude haute température(sup ou egal 65°C)': 2835,
  'Radiateur monotube sans robinet thermostatique sur réseau individuel eau chaude basse ou moyenne température(inf 65°C)': 2795,
  'Radiateur monotube avec robinet thermostatique sur réseau collectif eau chaude basse ou moyenne température(inf 65°C)': 1418,
  'Radiateur monotube avec robinet thermostatique sur réseau individuel eau chaude basse ou moyenne température(inf 65°C)': 1414,
  'Plancher rayonnant électrique avec régulation terminale': 1161,
  "Soufflage d'air chaud (air soufflé) avec distribution par réseau aéraulique": 1140,
  'Plancher rayonnant électrique sans régulation': 1004,
  'Plancher chauffant sur réseau individuel eau chaude basse ou moyenne température(inf 65°C)': 629,
  'Radiateur gaz à ventouse ou sur conduit de fumée': 343,
  'Convecteur bi-jonction': 287,
  'Autres équipements': 286,
  "Soufflage d'air chaud (air soufflé) avec distribution par fluide frigorigène": 216,
  'Plafond rayonnant électrique avec régulation terminale': 140,
  "Soufflage d'air chaud sans réseau de distribution (ventiloconvecteur éléctrique)": 131,
  'Radiateur avec distribution par fluide frigorigène (à détente directe)': 126,
  'Plafond chauffant sur réseau collectif eau chaude haute température(sup ou egal 65°C)': 82,
  'Poêle bois': 67,
  'Plafond chauffant sur réseau collectif eau chaude basse ou moyenne température(inf 65°C)': 50,
  'Plafond rayonnant électrique sans régulation': 42,
  "Soufflage d'air chaud (Ventiloconvecteur) sur réseau collectif eau chaude basse ou moyenne température(inf 65°C)": 14,
  'Plancher chauffant avec distribution par fluide frigorigène (plancher chauffant à détente directe)': 13,
  'Plafond chauffant sur réseau individuel eau chaude haute température(sup ou egal 65°C)': 8,
  "Soufflage d'air chaud (Ventiloconvecteur) sur réseau collectif eau chaude haute température(sup ou egal 65°C)": 7,
  'Poêle GPL': 7,
  'Poêle charbon': 6,
  'Plafond chauffant sur réseau individuel eau chaude basse ou moyenne température(inf 65°C)': 3,
  'Plafond chauffant avec distribution par fluide frigorigène (Plafond chauffant à détente directe)': 2,
  "Soufflage d'air chaud (Ventiloconvecteur) sur réseau individuel eau chaude haute température(sup ou egal 65°C)": 2,
  'Poêle fioul': 1,
  "Soufflage d'air chaud (Ventiloconvecteur) sur réseau individuel eau chaude basse ou moyenne température(inf 65°C)": 1},
 'type_installation_chauffage_ndeg1_ademe': {'installation individuelle': 223591,
  'installation collective': 121489,
  'installation collective multi-bâtiment : modélisée comme un réseau de chaleur': 11706,
  <NA>: 10418,
  'installation hybride collective-individuelle (chauffage base + appoint individuel ou convecteur bi-jonction)': 1877},
 'arrondissement': {'15': 42875,
  '20': 34038,
  '17': 32789,
  '18': 31593,
  '11': 28572,
  '16': 27793,
  '12': 25208,
  '13': 23237,
  '19': 22422,
  '14': 20471,
  '10': 16435,
  '9': 10634,
  '7': 10248,
  '5': 10221,
  '6': 7289,
  '8': 7128,
  '3': 6324,
  '4': 5070,
  '2': 3972,
  '1': 2762},
 'type_installation_ecs_ademe': {'installation individuelle': 246985,
  'installation collective': 103853,
  <NA>: 12337,
  'installation collective multi-bâtiment : modélisée comme un réseau de chaleur': 5906},
 'type_batiment_ademe': {'appartement': 361830,
  'immeuble': 5752,
  'maison': 1499},
 'type_installation_chauffage_ademe': {'individuel': 221115,
  'collectif': 127368,
  'mixte (collectif-individuel)': 19098,
  <NA>: 1500},
 'configuration_installation_chauffage_ndeg1_ademe': {'Installation de chauffage simple': 356493,
  <NA>: 10418,
  'Installation de chauffage collectif avec Base + appoint': 1650,
  'Convecteurs bi-jonction': 276,
  'Installation de chauffage avec insert ou poêle bois en appoint': 158,
  'Installation de chauffage avec chaudière en relève de PAC': 47,
  'Installation de chauffage avec en appoint un insert ou poêle bois et un chauffage électrique dans la salle de bain (différent du chauffage principal)': 23,
  'Installation de chauffage avec chauffage solaire': 14,
  'Installation de chauffage par insert, poêle bois (ou biomasse) avec un chauffage électrique dans la salle de bain': 2},
 'usage_generateur_ndeg1_installation_ndeg1_ademe': {'chauffage': 212581,
  'chauffage + ecs': 146053,
  <NA>: 10418,
  'ecs': 29},
 'configuration_installation_ecs_ademe': {"Un seul système d'ECS sans solaire": 350975,
  <NA>: 12337,
  "Deux systèmes d'ECS dans une maison ou un appartement": 3913,
  "Un seul système d'ECS avec solaire": 1856},
 'methode_application_dpe_ademe': {'dpe appartement individuel': 289390,
  'dpe appartement généré à partir des données DPE immeuble': 72396,
  'dpe immeuble collectif': 5751,
  'dpe maison individuelle': 1499,
  "dpe issu d'une étude thermique réglementaire RT2012 bâtiment : appartement": 44,
  "dpe issu d'une étude thermique réglementaire RT2012 bâtiment : immeuble": 1},
 'type_installation_ecs_general_ademe': {'individuel': 255041,
  'collectif': 111413,
  <NA>: 1500,
  'mixte (collectif-individuel)': 1127},
 'type_energie_generateur_ndeg1_installation_ndeg1_ademe': {'Électricité': 164528,
  'Gaz naturel': 137740,
  'Réseau de Chauffage urbain': 50710,
  <NA>: 10418,
  'Fioul domestique': 5060,
  'GPL': 480,
  'Bois – Bûches': 90,
  'Bois – Granulés (pellets) ou briquettes': 26,
  'Propane': 16,
  'Charbon': 5,
  'Butane': 4,
  'Bois – Plaquettes forestières': 4},
 'type_generateur_ecs_ndeg1_ademe': {'Ballon électrique à accumulation vertical Catégorie B ou 2 étoiles': 58197,
  'Ballon électrique à accumulation vertical Autres ou inconnue': 54597,
  'Ballon électrique à accumulation horizontal': 37671,
  'Réseau de chaleur isolé': 36834,
  'Ballon électrique à accumulation vertical Catégorie C ou 3 étoiles': 33842,
  'Chaudière gaz standard 2001-2015': 25158,
  'Chaudière gaz à condensation après 2015': 24493,
  'Chaudière gaz à condensation 2001-2015': 17367,
  <NA>: 12337,
  'Chaudière gaz standard 1991-2000': 8680,
  'Chaudière gaz standard après 2015': 8548,
  'Chaudière gaz basse température 2001-2015': 8533,
  'Chaudière gaz classique avant 1981': 7086,
  'Chaudière(s) gaz multi bâtiment modélisée comme un réseau de chaleur': 6780,
  'chauffe-eau électrique instantané': 5109,
  'Chaudière gaz basse température après 2015': 4982,
  'Réseau de chaleur non isolé': 2694,
  'Chauffe-eau gaz à production instantanée 2001-2015': 2287,
  'Chaudière gaz classique 1986-1990': 1501,
  'Chauffe-eau gaz à production instantanée après 2015': 1270,
  'Chaudière gaz basse température 1991-2000': 1267,
  'Chaudière fioul standard 1991-2015': 1119,
  'Chaudière gaz à condensation 1986-2000': 1112,
  'Chauffe-eau gaz à production instantanée 1990-2000': 734,
  'Chaudière fioul classique avant 1970': 672,
  'Chaudière gaz classique 1981-1985': 662,
  'Chaudière électrique': 612,
  'réseau de chaleur non répertorié ou inconnu': 547,
  'CET sur air extérieur après 2014': 503,
  'Chaudière(s) bois multi bâtiment modélisée comme un réseau de chaleur': 397,
  'Chauffe-eau gaz à production instantanée avant 1980': 349,
  'Chaudière gaz à condensation 1981-1985': 314,
  'CET sur air ambiant (sur local non chauffé) après 2014': 310,
  "système collectif par défaut en abscence d'information : chaudière fioul pénalisante": 277,
  'Chaudière fioul classique 1981-1990': 265,
  'Chaudière fioul basse température 1991-2015': 227,
  'PAC double service après 2014': 206,
  'CET sur air extrait après 2014': 176,
  'Chaudière fioul à condensation 1996-2015': 172,
  'Chaudière fioul classique 1970-1975': 155,
  'Chaudière gpl/propane/butane classique avant 1981': 138,
  'Chauffe-eau gaz à production instantanée 1981-1989': 111,
  'Chaudière fioul classique 1976-1980': 99,
  'Chaudière fioul standard après 2015': 90,
  'Chaudière gpl/propane/butane standard après 2015': 54,
  'Chaudière fioul à condensation après 2015': 46,
  'Accumulateur gaz classique après 2000': 42,
  'CET sur air ambiant (sur local non chauffé) avant 2010': 41,
  'Chaudière gpl/propane/butane standard 2001-2015': 40,
  'PAC double service 2010-2014': 39,
  'Chaudière fioul basse température après 2015': 28,
  'pompe à chaleur hybride : partie chaudière Chaudière gaz à condensation après 2015': 27,
  'Accumulateur gaz à condensation après 2000': 25,
  'Accumulateur gaz classique avant 1990': 24,
  'Pompe(s) à chaleur multi bâtiment modélisée comme un réseau de chaleur': 23,
  'Chaudière(s) fioul multi bâtiment modélisée comme un réseau de chaleur': 22,
  'PAC double service avant 2010': 21,
  'CET sur air extérieur avant 2010': 19,
  'Chaudière bois granulés 2013-2019': 19,
  'Accumulateur gaz classique 1990-2000': 19,
  'CET sur air extérieur 2010-2014': 18,
  'autre système à combustion gaz': 17,
  'Chaudière gpl/propane/butane classique 1986-1990': 14,
  'CET sur air ambiant (sur local non chauffé) 2010-2014': 13,
  'CET sur air extrait avant 2010': 12,
  'Chaudière gpl/propane/butane standard 1991-2000': 12,
  'Chaudière gpl/propane/butane basse température 2001-2015': 5,
  'Accumulateur gaz à condensation 1996-2000': 3,
  'pompe à chaleur hybride : partie chaudière Chaudière gaz à condensation 2001-2015': 3,
  'Chaudière gpl/propane/butane à condensation après 2015': 3,
  'Chauffe-eau gpl/propane/butane à production instantanée après 2015': 2,
  'autre système à combustion bois': 2,
  'pompe à chaleur hybride : partie chaudière Chaudière bois granulés 2013-2019': 2,
  'Chauffe-eau gpl/propane/butane à production instantanée avant 1980': 2,
  'CET sur air extrait 2010-2014': 1,
  'Chauffe-eau gpl/propane/butane à production instantanée 1990-2000': 1,
  'Chaudière bois granulés après 2019': 1,
  'Chaudière gpl/propane/butane à condensation 2001-2015': 1},
 'type_generateur_ndeg1_installation_ndeg1_ademe': {'Convecteur électrique NFC, NF** et NF***': 47322,
  'Radiateur électrique à accumulation': 39221,
  'Réseau de chaleur isolé': 38386,
  'radiateur électrique NFC, NF** et NF***': 32607,
  'Panneau rayonnant électrique NFC, NF** et NF***': 30708,
  'Chaudière gaz à condensation après 2015': 29740,
  'Chaudière gaz standard 2001-2015': 29555,
  'Chaudière gaz à condensation 2001-2015': 20153,
  'Chaudière gaz standard 1991-2000': 11574,
  <NA>: 10418,
  'Chaudière gaz basse température 2001-2015': 9934,
  'Chaudière gaz standard après 2015': 9799,
  'Autres émetteurs à effet joule': 9698,
  'Chaudière gaz classique avant 1981': 9570,
  'Chaudière(s) gaz multi bâtiment modélisée comme un réseau de chaleur': 9130,
  'Réseau de chaleur non isolé': 7531,
  'Chaudière gaz basse température après 2015': 5405,
  'Chaudière gaz classique 1986-1990': 2021,
  'Chaudière fioul standard 1991-2015': 1817,
  'Chaudière gaz basse température 1991-2000': 1796,
  'Chaudière gaz à condensation 1986-2000': 1450,
  'Plancher ou plafond rayonnant électrique avec régulation terminale': 1278,
  'Chaudière fioul classique avant 1970': 1153,
  'Plancher ou plafond rayonnant électrique sans régulation terminale': 966,
  'Chaudière électrique': 897,
  'Chaudière gaz classique 1981-1985': 863,
  'PAC air/air installée à partir de 2015': 835,
  'réseau de chaleur non répertorié ou inconnu': 573,
  'Chaudière fioul classique 1981-1990': 463,
  'Chaudière gaz à condensation 1981-1985': 450,
  "système collectif par défaut en abscence d'information : chaudière fioul pénalisante": 390,
  'Chaudière fioul basse température 1991-2015': 338,
  'convecteur bi-jonction': 307,
  'radiateur à gaz indépendant ou autonome avant 2006': 295,
  'Chaudière fioul classique 1970-1975': 260,
  'Chaudière fioul à condensation 1996-2015': 251,
  'Chaudière fioul classique 1976-1980': 186,
  'PAC air/air installée entre 2008 et 2014': 181,
  'PAC air/air installée avant 2008': 146,
  'Chaudière gpl/propane/butane standard 2001-2015': 125,
  'Chaudière fioul standard après 2015': 108,
  'Chaudière gpl/propane/butane à condensation après 2015': 104,
  'PAC air/eau installée avant 2008': 80,
  'autre système à combustion gaz': 79,
  'Chaudière gpl/propane/butane basse température 2001-2015': 76,
  'PAC air/eau installée après 2017': 60,
  'PAC air/eau installée entre 2015 et 2016': 60,
  'Chaudière fioul à condensation après 2015': 58,
  'Chaudière gpl/propane/butane classique avant 1981': 52,
  'radiateur à gaz indépendant ou autonome après 2006': 50,
  'Chaudière(s) fioul multi bâtiment modélisée comme un réseau de chaleur': 40,
  'Chaudière gpl/propane/butane standard après 2015': 39,
  'Chaudière fioul basse température après 2015': 36,
  'pompe à chaleur hybride : partie pompe à chaleur PAC air/eau installée après 2017': 32,
  'Chaudière gpl/propane/butane à condensation 2001-2015': 31,
  'Chaudière gpl/propane/butane standard 1991-2000': 25,
  'Pompe(s) à chaleur multi bâtiment modélisée comme un réseau de chaleur': 24,
  'Chaudière bois granulés 2013-2019': 22,
  'Poêle fioul ou GPL ou charbon': 20,
  'PAC air/eau installée entre 2008 et 2014': 20,
  'PAC eau/eau installée après 2017': 19,
  'PAC eau/eau installée entre 2015 et 2016': 18,
  'Chaudière(s) bois multi bâtiment modélisée comme un réseau de chaleur': 14,
  'PAC eau/eau installée entre 2008 et 2014': 12,
  'autre système à combustion bois': 12,
  'PAC eau glycolée/eau installée entre 2008 et 2014': 11,
  'Foyer fermé installé avant 1990': 11,
  'Chaudière gpl/propane/butane basse température après 2015': 11,
  'Chaudière gpl/propane/butane classique 1986-1990': 11,
  'générateur à air chaud à combustion standard a partir de 2006': 9,
  'générateur à air chaud à combustion avant 2006': 8,
  'Poêle bûche installé installé de 2007 à 2017 avec label flamme verte': 8,
  'Chaudière gpl/propane/butane basse température 1991-2000': 8,
  'PAC eau/eau installée avant 2008': 7,
  'PAC géothermique installée entre 2008 et 2014': 7,
  'Poêle bûche installé entre 1990 et 2004': 7,
  'Poêle bûche installé installé à partir de 2018 avec label flamme verte': 6,
  'insert installé avant 1990': 6,
  'PAC géothermique installée après 2017': 6,
  'pompe à chaleur hybride : partie pompe à chaleur PAC eau/eau installée après 2017': 6,
  'Poêle bûche installé à partir de 2005 sans label flamme verte': 5,
  'PAC eau glycolée/eau installée après 2017': 5,
  'Poêle bûche installé avant 1990': 5,
  'Cuisinière installé avant 1990': 5,
  'Poêle à granulés flamme verte installé à partir de 2020': 4,
  'Poêle à granulés flamme verte installé entre 2012 et 2019': 4,
  'pompe à chaleur hybride : partie chaudière Chaudière gaz à condensation 2001-2015': 4,
  'Chaudière gpl/propane/butane classique 1981-1985': 3,
  'Chaudière bois bûche 2013-2017': 3,
  'Foyer fermé installé installé à partir de 2018 avec label flamme verte': 3,
  'PAC géothermique installée avant 2008': 3,
  'autre système à combustion fioul': 3,
  'insert installé installé à partir de 2018 avec label flamme verte': 3,
  'insert installé installé de 2007 à 2017 avec label flamme verte': 2,
  'insert installé à partir de 2005 sans label flamme verte': 2,
  'pompe à chaleur hybride : partie chaudière Chaudière gaz à condensation après 2015': 2,
  'Chaudière gpl/propane/butane à condensation 1981-1985': 2,
  'générateur à air chaud à combustion à condensation a partir de 2006': 2,
  'Chaudière bois bûche avant 1978': 2,
  'insert installé entre 1990 et 2004': 2,
  'poêle à bois bouilleur bûche installé à partir de 2012': 2,
  'Foyer fermé installé entre 1990 et 2004': 1,
  'Chaudière bois plaquette après 2019': 1,
  'PAC eau glycolée/eau installée avant 2008': 1,
  'autre système thermodynamique gaz': 1,

### Application encodage dataframe v1 (recap)

In [7]:
cols_qualite_ademe_to_oe = [
    'qualite_isolation_menuiseries_ademe',
    'qualite_isolation_murs_ademe',
    'qualite_isolation_plancher_haut_comble_perdu_ademe',
    'qualite_isolation_enveloppe_ademe',
    'qualite_isolation_plancher_bas_ademe',
    'qualite_isolation_plancher_haut_toit_terrase_ademe',
    'indicateur_confort_ete_ademe'
    ]

cols_0_1_ademe_to_oe = [
    'logement_traversant_0_1_ademe',
    'presence_brasseur_air_0_1_ademe',
    'protection_solaire_exterieure_0_1_ademe',
    'inertie_lourde_0_1_ademe',
    'isolation_toiture_0_1_ademe',
    'appartement_non_visite_0_1_ademe'
    ]

cols_etiquettes_ademe_to_oe = ['etiquette_ges_ademe', 'etiquette_dpe_ademe']
col_classe_inertie_bat_ademe_to_oe = ['classe_inertie_batiment_ademe']
col_periode_construction_to_oe = ['periode_construction_ademe']

# ---------
get_col_mapping = lambda colname, mapping: {'col': colname, 'mapping': mapping}

mapping_qualite_ademe_oe = {'insuffisante': 1, 'moyenne': 2, 'bonne': 3, 'très bonne': 4, '<NA>': -1}
mapping_0_1_ademe_oe = {'True': 1, 'False': 0, '<NA>': -1} 
mapping_etiquettes_ademe_oe = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, '<NA>': -1}
mapping_classe_inertie_bat_ademe_oe = {'Légère': 1, 'Moyenne': 2, 'Lourde': 3, 'Très lourde': 4, '<NA>': -1}
mapping_periode_construction_oe = {
    "avant 1948": 1,
    "1948-1974": 2,
    "1975-1977": 3,
    "1978-1982": 4,
    "1983-1988": 5,
    "1989-2000": 6,
    "2001-2005": 7,
    "2006-2012": 8,
    "2013-2021": 9,
    "après 2021": 10,
    '<NA>': -1
    }

# ---- ordinal encoder all in one

cols_to_ordinal_encode = cols_qualite_ademe_to_oe + cols_0_1_ademe_to_oe + cols_etiquettes_ademe_to_oe + col_classe_inertie_bat_ademe_to_oe + col_periode_construction_to_oe

full_oe_mapping = [get_col_mapping(c, mapping_qualite_ademe_oe) for c in cols_qualite_ademe_to_oe]
full_oe_mapping += [get_col_mapping(c, mapping_0_1_ademe_oe) for c in cols_0_1_ademe_to_oe]
full_oe_mapping += [get_col_mapping(c, mapping_etiquettes_ademe_oe) for c in cols_etiquettes_ademe_to_oe]
full_oe_mapping += [get_col_mapping(c, mapping_classe_inertie_bat_ademe_oe) for c in col_classe_inertie_bat_ademe_to_oe]
full_oe_mapping += [get_col_mapping(c, mapping_periode_construction_oe) for c in col_periode_construction_to_oe]

other_cols_to_label_encode = list(set(df_clean_v1.select_dtypes(include='string').columns) - set(cols_to_ordinal_encode))

In [7]:
get_n_classes = lambda data, colname: len(data[colname].unique())

In [12]:
numerisation_pipeline = ColumnTransformer(
        transformers=[
            # ('log_transformer', LogTransformer(columns=quant_features_names), quant_features_names),
            ('ordinal_encoding', ce.OrdinalEncoder(mapping=full_oe_mapping), cols_to_ordinal_encode),
            ('label_encoding', ce.BinaryEncoder(base=112), other_cols_to_label_encode)
        ], 
        remainder='passthrough',
        verbose_feature_names_out=False
    )

df_clean_v1_copy = df_clean_v1.copy()

df_clean_v1_copy = numerize(df_clean_v1_copy, numerisation_pipeline)
df_clean_v1_copy.head()

,qualite_isolation_menuiseries_ademe,qualite_isolation_murs_ademe,qualite_isolation_plancher_haut_comble_perdu_ademe,qualite_isolation_enveloppe_ademe,qualite_isolation_plancher_bas_ademe,qualite_isolation_plancher_haut_toit_terrase_ademe,indicateur_confort_ete_ademe,logement_traversant_0_1_ademe,presence_brasseur_air_0_1_ademe,protection_solaire_exterieure_0_1_ademe,...,conso_chauffage_depensier_e_primaire_ademe,score_ban_ademe,surface_habitable_immeuble_ademe,annee_construction_ademe,nombre_niveau_immeuble_ademe,consommation_annuelle_totale_de_l_adresse_mwh_enedis_with_ban,consommation_annuelle_moyenne_de_la_commune_mwh_enedis_with_ban,lon_enedis_with_ban,lat_enedis_with_ban,consommation_annuelle_moyenne_par_logement_de_l_adresse_kwh_enedis_with_ban
0,4,1.0,4.0,1,4.0,-1.0,-1.0,1.0,0.0,1.0,...,20573.599609,0.72,2587.0,1947.0,7.0,78.292,2.686,2.328325,48.84874,4350.0
1,1,1.0,1.0,4,4.0,-1.0,-1.0,0.0,0.0,0.0,...,2312.300049,0.72,2587.0,1947.0,7.0,78.292,2.686,2.328325,48.84874,4350.0
2,1,1.0,4.0,1,4.0,-1.0,-1.0,1.0,0.0,0.0,...,41476.398438,0.72,2587.0,1947.0,7.0,78.292,2.686,2.328325,48.84874,4350.0
3,2,1.0,1.0,3,4.0,-1.0,-1.0,0.0,0.0,0.0,...,4481.700195,0.72,2587.0,1947.0,7.0,78.292,2.686,2.328325,48.84874,4350.0
4,3,1.0,3.0,4,4.0,-1.0,-1.0,1.0,0.0,0.0,...,4594.100098,0.72,2587.0,1947.0,7.0,78.292,2.686,2.328325,48.84874,4350.0

In [14]:
df_clean_v1_copy.dtypes.value_counts()

float32    62
int32      27
Name: count, dtype: int64

### Encodage dataframe v2 (use correlation with target selection)

In [26]:
df = load_parquet_data('../ressources/data/2_intermediary/enedis_ban_ademe_extract_PARIS_2022.parquet')

pipeline = Nettoyage(df)

pipeline.run(use_target_correlation_selection=True)
df_clean_v2 = pipeline.df

del df

Loading parquet data from : ../ressources/data/2_intermediary/enedis_ban_ademe_extract_PARIS_2022.parquet..
-> Delete cols mano..
-> Delete NaN cols..
Le dataframe contient initialement 250 colonnes et 464576 lignes.
Start processing : columns identification..
Il y a 76 colonnes vides à au moins, 90.0%, 55 colonnes avec une entropie de 0 ou 1 et 13 colonnes inutiles
Start processing : columns deleting ...
Il reste 146 colonnes et 375231 lignes.
-> Start object columns auto casting..
End casting
-> Fill pd.NA for float dtypes..
Done fillnan !
Les colonnes suivantes ont une corrélation supérieure à 0.9 : ['emission_ges_chauffage_energie_ndeg1_ademe', 'conso_chauffage_depensier_installation_chauffage_ndeg1_ademe', 'conso_chauffage_installation_chauffage_ndeg1_ademe', 'emission_ges_5_usages_energie_ndeg1_ademe', 'cout_refroidissement_depensier_ademe', 'emission_ges_eclairage_ademe', 'conso_e_finale_depensier_generateur_ecs_ndeg1_ademe', 'cout_chauffage_energie_ndeg1_ademe', 'conso_chauffage_generateur_ndeg1_installation_ndeg1_ademe', 'emission_ges_ecs_ademe', 'emission_ges_ecs_depensier_ademe', 'emission_ges_5_usages_ademe', 'apports_internes_saison_chauffe_ademe', 'conso_e_finale_generateur_ecs_ndeg1_ademe', 'deperditions_enveloppe_ademe', 'conso_refroidissement_e_finale_ademe', 'surface_habitable_desservie_par_installation_ecs_ademe', 'emission_ges_auxiliaires_ademe', 'conso_ecs_depensier_e_finale_ademe', 'cout_chauffage_depensier_ademe', 'conso_chauffage_depensier_e_primaire_ademe', 'conso_refroidissement_e_primaire_ademe', 'conso_ecs_e_finale_ademe', 'cout_total_5_usages_energie_ndeg2_ademe', 'conso_e_finale_depensier_installation_ecs_ademe', 'cout_total_5_usages_ademe', 'cout_eclairage_ademe', 'emission_ges_chauffage_energie_ndeg2_ademe', 'conso_chauffage_e_finale_energie_ndeg1_ademe', 'conso_5_usages_e_finale_energie_ndeg1_ademe', 'cout_refroidissement_ademe', 'deperditions_murs_ademe', 'surface_chauffee_installation_chauffage_ndeg1_ademe', 'cout_ecs_ademe', 'conso_eclairage_e_primaire_ademe', 'conso_chauffage_e_finale_ademe', 'conso_chauffage_depensier_e_finale_ademe', 'conso_eclairage_e_finale_ademe', 'conso_ecs_e_finale_energie_ndeg1_ademe', 'conso_chauffage_depensier_generateur_ndeg1_installation_ndeg1_ademe', 'besoin_chauffage_ademe', 'conso_ecs_e_finale_energie_ndeg2_ademe', 'cout_chauffage_ademe', 'conso_chauffage_e_primaire_ademe', 'deperditions_renouvellement_air_ademe', 'emission_ges_chauffage_depensier_ademe', 'conso_5_usages_e_finale_ademe', 'conso_ecs_depensier_e_primaire_ademe', 'conso_5_usages_e_primaire_ademe', 'conso_auxiliaires_e_finale_ademe', 'emission_ges_chauffage_ademe', 'emission_ges_ecs_energie_ndeg1_ademe', 'cout_ecs_depensier_ademe']
Les colonnes suivantes ont été supprimées : ['emission_ges_chauffage_energie_ndeg1_ademe', 'conso_chauffage_depensier_installation_chauffage_ndeg1_ademe', 'conso_chauffage_installation_chauffage_ndeg1_ademe', 'emission_ges_5_usages_energie_ndeg1_ademe', 'cout_refroidissement_depensier_ademe', 'emission_ges_eclairage_ademe', 'conso_e_finale_depensier_generateur_ecs_ndeg1_ademe', 'cout_chauffage_energie_ndeg1_ademe', 'conso_chauffage_generateur_ndeg1_installation_ndeg1_ademe', 'emission_ges_ecs_ademe', 'emission_ges_ecs_depensier_ademe', 'emission_ges_5_usages_ademe', 'apports_internes_saison_chauffe_ademe', 'conso_e_finale_generateur_ecs_ndeg1_ademe', 'deperditions_enveloppe_ademe', 'conso_refroidissement_e_finale_ademe', 'surface_habitable_desservie_par_installation_ecs_ademe', 'emission_ges_auxiliaires_ademe', 'conso_ecs_depensier_e_finale_ademe', 'cout_chauffage_depensier_ademe', 'conso_chauffage_depensier_e_primaire_ademe', 'conso_refroidissement_e_primaire_ademe', 'conso_ecs_e_finale_ademe', 'cout_total_5_usages_energie_ndeg2_ademe', 'conso_e_finale_depensier_installation_ecs_ademe', 'cout_total_5_usages_ademe', 'cout_eclairage_ademe', 'emission_ges_chauffage_energie_ndeg2_ademe', 'conso_chauffage_e_finale_energie_ndeg1_ademe', 'conso_5_usages_e_finale_energie_ndeg1_ademe', 'cout_refroidissement_ademe', 'deperditions_murs_ademe', 'surface_chauffee_installation_chauffage_ndeg1_ademe', 'cout_ecs_ademe', 'conso_eclairage_e_primaire_ademe', 'conso_chauffage_e_finale_ademe', 'conso_chauffage_depensier_e_finale_ademe', 'conso_eclairage_e_finale_ademe', 'conso_ecs_e_finale_energie_ndeg1_ademe', 'conso_chauffage_depensier_generateur_ndeg1_installation_ndeg1_ademe', 'besoin_chauffage_ademe', 'conso_ecs_e_finale_energie_ndeg2_ademe', 'cout_chauffage_ademe', 'conso_chauffage_e_primaire_ademe', 'deperditions_renouvellement_air_ademe', 'emission_ges_chauffage_depensier_ademe', 'conso_5_usages_e_finale_ademe', 'conso_ecs_depensier_e_primaire_ademe', 'conso_5_usages_e_primaire_ademe', 'conso_auxiliaires_e_finale_ademe', 'emission_ges_chauffage_ademe', 'emission_ges_ecs_energie_ndeg1_ademe', 'cout_ecs_depensier_ademe']
Il reste 93 colonnes
Il y a 4 colonnes de dates à supprimer..
Le nettoyage a duré : 0:02:34.064125
====================================================================================================

In [27]:
df_clean_v2.dtypes.value_counts()

float32           50
string[python]    39
Name: count, dtype: int64

In [30]:
assert all(_ in df_clean_v2 for _ in  cols_to_ordinal_encode + other_cols_to_label_encode )

In [21]:
numerisation_pipeline_v2 = ColumnTransformer(
        transformers=[
            # ('log_transformer', LogTransformer(columns=quant_features_names), quant_features_names),
            ('ordinal_encoding', ce.OrdinalEncoder(mapping=full_oe_mapping), cols_to_ordinal_encode),
            ('label_encoding', ce.BinaryEncoder(base=112), other_cols_to_label_encode)
        ], 
        remainder='passthrough',
        verbose_feature_names_out=False
    )

In [22]:
df_clean_v2_copy = df_clean_v2.copy()

df_clean_v2_copy = numerize(df_clean_v2_copy, numerisation_pipeline_v2)

In [25]:
df_clean_v2_copy.dtypes.value_counts()

float32    62
int32      27
Name: count, dtype: int64